### ISSUE TITLE
Cannot find module './node_modules/oauth/lib/oauth2'

### ISSUE THREAD

**Issue by djgalloway** [ether/ep_oauth#6]
Getting this upon startup.

```
^[[31m[2021-09-22 11:52:23.150] [ERROR] console - ^[[39mFailed to load hook function "/home/etherpad/etherpad-lite-1.8.14/node_modules/ep_oauth/auth:authenticate" for plugin "ep_oauth" part "ep_oauth" hook set "hooks" hook "authenticate": Error: Cannot find module './node_modules/oauth/lib/oauth2'
Require stack:
- /home/etherpad/etherpad-lite-1.8.14/node_modules/ep_oauth/auth.js
- /home/etherpad/etherpad-lite-1.8.14/src/static/js/pluginfw/shared.js
- /home/etherpad/etherpad-lite-1.8.14/src/static/js/pluginfw/plugins.js
- /home/etherpad/etherpad-lite-1.8.14/src/node/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/etherpad/etherpad-lite-1.8.14/node_modules/ep_oauth/auth.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
```

**Comment by JohnMcLear** [comment]
How did you install the plugin?

**Comment by djgalloway** [comment]
Via `/admin/plugins`

**Comment by JohnMcLear** [comment]
Things to please try.

1. Make sure you have the required blob in ``settings.json`` as per the docs.
2. See if any other errors/warnings are coming up in console on startup.
3. Try uninstall/reinstall the plugin, keeping an eye on log output.

If you have no dice please let me know and I will debug ASAP.

**Comment by JohnMcLear** [comment]
Ah balls.

```
[2021-09-22 19:37:21.476] [INFO] http - Successful authentication from IP 127.0.0.1 for user admin
[2021-09-22 19:37:21.583] [ERROR] console - Error: Request aborted
    at onaborted (/home/jose/etherpad-lite/src/node_modules/express/lib/response.js:1025:15)
    at Immediate.<anonymous> (/home/jose/etherpad-lite/src/node_modules/express/lib/response.js:1067:9)
    at processImmediate (internal/timers.js:464:21)
[2021-09-22 19:37:31.587] [INFO] plugins - Installing plugin ep_oauth...
[2021-09-22 19:37:34.921] [ERROR] runCmd|npm - npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2021-09-22 19:37:35.048] [ERROR] runCmd|npm - npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[2021-09-22 19:37:39.442] [ERROR] runCmd|npm - npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
[2021-09-22 19:37:39.504] [ERROR] runCmd|npm - npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
[2021-09-22 19:37:41.075] [INFO] runCmd|npm - 
[2021-09-22 19:37:41.075] [INFO] runCmd|npm - > keytar@7.7.0 install /home/jose/etherpad-lite/node_modules/keytar
[2021-09-22 19:37:41.075] [INFO] runCmd|npm - > prebuild-install || npm run build
[2021-09-22 19:37:41.076] [INFO] runCmd|npm - 
[2021-09-22 19:37:41.183] [INFO] runCmd|npm - 
[2021-09-22 19:37:41.184] [INFO] runCmd|npm - > sqlite3@5.0.2 install /home/jose/etherpad-lite/node_modules/sqlite3
[2021-09-22 19:37:41.184] [INFO] runCmd|npm - > node-pre-gyp install --fallback-to-build
[2021-09-22 19:37:41.184] [INFO] runCmd|npm - 
[2021-09-22 19:37:41.311] [ERROR] runCmd|npm - node-pre-gyp WARN Using request for node-pre-gyp https download 
[2021-09-22 19:37:42.483] [INFO] runCmd|npm - [sqlite3] Success: "/home/jose/etherpad-lite/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
[2021-09-22 19:37:42.506] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/home/jose/etherpad-lite/package.json'
[2021-09-22 19:37:42.510] [ERROR] runCmd|npm - npm WARN etherpad-lite No description
[2021-09-22 19:37:42.514] [ERROR] runCmd|npm - npm WARN etherpad-lite No repository field.
[2021-09-22 19:37:42.518] [ERROR] runCmd|npm - npm WARN etherpad-lite No README data
[2021-09-22 19:37:42.523] [ERROR] runCmd|npm - npm WARN etherpad-lite No license field.
[2021-09-22 19:37:42.524] [ERROR] runCmd|npm - 
[2021-09-22 19:37:42.525] [INFO] runCmd|npm - + ep_oauth@0.0.11
[2021-09-22 19:37:42.525] [INFO] runCmd|npm - added 150 packages from 191 contributors and audited 1088 packages in 10.646s
[2021-09-22 19:37:42.768] [INFO] runCmd|npm - 
[2021-09-22 19:37:42.768] [INFO] runCmd|npm - 86 packages are looking for funding
[2021-09-22 19:37:42.768] [INFO] runCmd|npm -   run `npm fund` for details
[2021-09-22 19:37:42.768] [INFO] runCmd|npm - 
[2021-09-22 19:37:42.768] [INFO] runCmd|npm - found 7 vulnerabilities (2 moderate, 5 high)
[2021-09-22 19:37:42.768] [INFO] runCmd|npm -   run `npm audit fix` to fix them, or `npm audit` for details
[2021-09-22 19:37:42.798] [INFO] plugins - Successfully installed plugin ep_oauth
[2021-09-22 19:37:42.798] [INFO] plugins - Running npm to get a list of installed plugins...
[2021-09-22 19:37:44.319] [INFO] plugins - Loading plugin ep_etherpad-lite...
[2021-09-22 19:37:44.319] [INFO] plugins - Loading plugin ep_oauth...
[2021-09-22 19:37:44.320] [INFO] plugins - Loaded 2 plugins
[2021-09-22 19:37:44.373] [ERROR] console - Failed to load hook function "/home/jose/etherpad-lite/node_modules/ep_oauth/auth:authenticate" for plugin "ep_oauth" part "ep_oauth" hook set "hooks" hook "authenticate": Error: Cannot find module './node_modules/oauth/lib/oauth2'
Require stack:
- /home/jose/etherpad-lite/node_modules/ep_oauth/auth.js
- /home/jose/etherpad-lite/src/static/js/pluginfw/shared.js
- /home/jose/etherpad-lite/src/static/js/pluginfw/plugins.js
- /home/jose/etherpad-lite/src/node/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jose/etherpad-lite/node_modules/ep_oauth/auth.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[2021-09-22 19:37:44.373] [ERROR] console - Failed to load hook function "/home/jose/etherpad-lite/node_modules/ep_oauth/auth:authorize" for plugin "ep_oauth" part "ep_oauth" hook set "hooks" hook "authorize": Error: Cannot find module './node_modules/oauth/lib/oauth2'
Require stack:
- /home/jose/etherpad-lite/node_modules/ep_oauth/auth.js
- /home/jose/etherpad-lite/src/static/js/pluginfw/shared.js
- /home/jose/etherpad-lite/src/static/js/pluginfw/plugins.js
- /home/jose/etherpad-lite/src/node/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jose/etherpad-lite/node_modules/ep_oauth/auth.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[2021-09-22 19:37:44.373] [ERROR] console - Failed to load hook function "/home/jose/etherpad-lite/node_modules/ep_oauth/auth:expressConfigure" for plugin "ep_oauth" part "ep_oauth" hook set "hooks" hook "expressConfigure": Error: Cannot find module './node_modules/oauth/lib/oauth2'
Require stack:
- /home/jose/etherpad-lite/node_modules/ep_oauth/auth.js
- /home/jose/etherpad-lite/src/static/js/pluginfw/shared.js
- /home/jose/etherpad-lite/src/static/js/pluginfw/plugins.js
- /home/jose/etherpad-lite/src/node/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jose/etherpad-lite/node_modules/ep_oauth/auth.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[2021-09-22 19:37:44.382] [INFO] console - settings loaded from: /home/jose/etherpad-lite/settings.json
```

**Comment by JohnMcLear** [comment]
https://github.com/ether/ep_oauth/commit/900c4a312234232ae703e082aabc57bb974b3fb5

This should now be resolved, it will auto-test then auto-publish. 

It's a one line fix if you want to temp monkey patch and test to confirm, I will close either way and if it's still an issue just let me know and I will re-open.

**Comment by djgalloway** [comment]
Nice!  Thank you for the prompt fix!

**Comment by djgalloway** [comment]
Sorry to bother again but does something else need to be done to notify Etherpad that the plugin has been updated?  I'm still seeing 0.0.11 in the Plugin Manager Web UI.

**Comment by JohnMcLear** [comment]
https://www.npmjs.com/package/ep_oauth shows 0.0.12..

https://static.etherpad.org/index.html shows 0.0.11

@Gared any idea what's broken here?

**Comment by Gared** [comment]
@JohnMcLear The replication was broken. I don't exactly know why, but the last update was on 15th September. I fixed it, but it will take some time to replicate all changes until now

**Comment by JohnMcLear** [comment]
Yikes!  Thanks man

**Comment by djgalloway** [comment]
Hey there.  I see the new version in the Plugin Manager but can't seem to get it installed despite the log indicating otherwise.

```
[2021-10-27 13:40:38.053] [DEBUG] runCmd - Executing command: npm install --no-save --legacy-peer-deps ep_oauth
[2021-10-27 13:40:38.053] [DEBUG] runCmd - cwd: /home/etherpad/etherpad-lite-1.8.14
[2021-10-27 13:40:38.054] [DEBUG] runCmd - PATH=/home/etherpad/etherpad-lite-1.8.14/src/node_modules/.bin:/home/etherpad/etherpad-lite-1.8.14/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2021-10-27 13:40:44.580] [ERROR] runCmd|npm - npm WARN enoent ENOENT: no such file or directory, open '/home/etherpad/etherpad-lite-1.8.14/package.json'
[2021-10-27 13:40:44.588] [ERROR] runCmd|npm - npm WARN etherpad-lite-1.8.14 No description
[2021-10-27 13:40:44.595] [ERROR] runCmd|npm - npm WARN etherpad-lite-1.8.14 No repository field.
[2021-10-27 13:40:44.604] [ERROR] runCmd|npm - npm WARN etherpad-lite-1.8.14 No README data
[2021-10-27 13:40:44.612] [ERROR] runCmd|npm - npm WARN etherpad-lite-1.8.14 No license field.
[2021-10-27 13:40:44.613] [ERROR] runCmd|npm - 
[2021-10-27 13:40:44.767] [INFO] runCmd|npm - + ep_oauth@0.0.12
[2021-10-27 13:40:44.767] [INFO] runCmd|npm - updated 1 package and audited 1268 packages in 6.235s
[2021-10-27 13:40:45.404] [INFO] runCmd|npm - 
[2021-10-27 13:40:45.405] [INFO] runCmd|npm - 63 packages are looking for funding
[2021-10-27 13:40:45.405] [INFO] runCmd|npm -   run `npm fund` for details
[2021-10-27 13:40:45.405] [INFO] runCmd|npm - 
[2021-10-27 13:40:45.407] [INFO] runCmd|npm - found 81 vulnerabilities (33 moderate, 48 high)
[2021-10-27 13:40:45.407] [INFO] runCmd|npm -   run `npm audit fix` to fix them, or `npm audit` for details
[2021-10-27 13:40:45.446] [DEBUG] runCmd - Command returned successfully: npm install --no-save --legacy-peer-deps ep_oauth
[2021-10-27 13:40:45.446] [INFO] plugins - Successfully installed plugin ep_oauth
[2021-10-27 13:40:45.446] [INFO] plugins - Running npm to get a list of installed plugins...
[2021-10-27 13:40:45.446] [DEBUG] runCmd - Executing command: npm ls --long --json --depth=0 --no-production
[2021-10-27 13:40:45.446] [DEBUG] runCmd - cwd: /home/etherpad/etherpad-lite-1.8.14
[2021-10-27 13:40:45.447] [DEBUG] runCmd - PATH=/home/etherpad/etherpad-lite-1.8.14/src/node_modules/.bin:/home/etherpad/etherpad-lite-1.8.14/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[2021-10-27 13:40:48.915] [DEBUG] runCmd - Command returned successfully: npm ls --long --json --depth=0 --no-production
[2021-10-27 13:40:48.930] [INFO] plugins - Loading plugin ep_adminpads2...
[2021-10-27 13:40:48.931] [INFO] plugins - Loading plugin ep_colibris_full_width...
[2021-10-27 13:40:48.931] [INFO] plugins - Loading plugin ep_etherpad-lite...
[2021-10-27 13:40:48.932] [INFO] plugins - Loading plugin ep_font_color...
[2021-10-27 13:40:48.932] [INFO] plugins - Loading plugin ep_font_size...
[2021-10-27 13:40:48.932] [INFO] plugins - Loading plugin ep_headings2...
[2021-10-27 13:40:48.933] [INFO] plugins - Loading plugin ep_markdown...
[2021-10-27 13:40:48.934] [INFO] plugins - Loaded 7 plugins
```

Do you see anything glaringly obvious?

**Comment by djgalloway** [comment]
Just upgraded to Ubuntu 20.04 w/ NodeJS 16.13.0-deb-1nodesource1.  No change.

**Comment by JohnMcLear** [comment]
If you remove then install instead of update does it work?  I'd try remove, restart, install

**Comment by djgalloway** [comment]
I think I made too many manual changes to the install.  I just started over with a fresh clone.

Now that that's fixed, any idea why `/auth/callback` would return a 404?

`[2021-10-27 16:11:08.172] [DEBUG] http - 404, GET /auth/callback`

**Comment by JohnMcLear** [comment]
;/ no.  Is it broken?

**Comment by djgalloway** [comment]
With the plugin installed and the `ep_oauth` blob in `settings.json` commented out, the site still functions fine.

`/auth/callback` just returns a 404.

If I uncomment the blob, I only get 502 gateway errors.

This etherpad-lite instance is behind an nginx reverse proxy if that matters.

Should the callback URL in the blob be the same callback URL in the github oauth app?
